# frozen_string_literal: true

module Plume
	class Token
		attr_reader :value

		def self.[](value) = new(value)

		def initialize(value)
			@value = value
		end

		def inspect = "#{self.class.name}[#{@value.inspect}]"

		def ==(other)
			other.is_a?(self.class) && other.value == @value
		end
	end

	KeywordToken 			= Class.new(Token)
	IDKeywordToken 		= Class.new(KeywordToken)

	TK 								= Module.new

	TK::ABORT					= Class.new(IDKeywordToken)
	TK::ACTION				= Class.new(IDKeywordToken)
	TK::ADD						= Class.new(KeywordToken)
	TK::AFTER					= Class.new(IDKeywordToken)
	TK::ALL						= Class.new(KeywordToken)
	TK::ALTER					= Class.new(KeywordToken)
	TK::ALWAYS				= Class.new(IDKeywordToken)
	TK::ANALYZE				= Class.new(IDKeywordToken)
	TK::AND						= Class.new(KeywordToken)
	TK::AS						= Class.new(KeywordToken)
	TK::ASC						= Class.new(IDKeywordToken)
	TK::ATTACH				= Class.new(IDKeywordToken)
	TK::AUTOINCR			= Class.new(KeywordToken)
	TK::BEFORE				= Class.new(IDKeywordToken)
	TK::BEGIN					= Class.new(IDKeywordToken)
	TK::BETWEEN				= Class.new(KeywordToken)
	TK::BITAND				= Class.new(Token)
	TK::BITNOT				= Class.new(Token)
	TK::BITOR					= Class.new(Token)
	TK::BLOB					= Class.new(Token)
	TK::BY						= Class.new(IDKeywordToken)
	TK::CASCADE				= Class.new(IDKeywordToken)
	TK::CASE					= Class.new(KeywordToken)
	TK::CAST					= Class.new(IDKeywordToken)
	TK::CHECK					= Class.new(KeywordToken)
	TK::COLLATE				= Class.new(KeywordToken)
	TK::COLUMNKW			= Class.new(IDKeywordToken)
	TK::COMMA					= Class.new(Token)
	TK::COMMIT				= Class.new(KeywordToken)
	TK::CONCAT				= Class.new(Token)
	TK::CONFLICT			= Class.new(IDKeywordToken)
	TK::CONSTRAINT		= Class.new(KeywordToken)
	TK::CREATE				= Class.new(KeywordToken)
	TK::CTIME_KW			= Class.new(IDKeywordToken)
	TK::CURRENT				= Class.new(IDKeywordToken)
	TK::DATABASE			= Class.new(IDKeywordToken)
	TK::DEFAULT				= Class.new(KeywordToken)
	TK::DEFERRABLE		= Class.new(KeywordToken)
	TK::DEFERRED			= Class.new(IDKeywordToken)
	TK::DELETE				= Class.new(KeywordToken)
	TK::DESC					= Class.new(IDKeywordToken)
	TK::DETACH				= Class.new(IDKeywordToken)
	TK::DISTINCT			= Class.new(KeywordToken)
	TK::DO						= Class.new(IDKeywordToken)
	TK::DOT						= Class.new(Token)
	TK::DROP					= Class.new(KeywordToken)
	TK::EACH					= Class.new(IDKeywordToken)
	TK::ELSE					= Class.new(KeywordToken)
	TK::END						= Class.new(IDKeywordToken)
	TK::EQ						= Class.new(Token)
	TK::ESCAPE				= Class.new(KeywordToken)
	TK::EXCEPT				= Class.new(KeywordToken)
	TK::EXCLUDE				= Class.new(IDKeywordToken)
	TK::EXCLUSIVE			= Class.new(IDKeywordToken)
	TK::EXISTS				= Class.new(KeywordToken)
	TK::EXPLAIN				= Class.new(IDKeywordToken)
	TK::FAIL					= Class.new(IDKeywordToken)
	TK::FILTER				= Class.new(KeywordToken)
	TK::FIRST					= Class.new(IDKeywordToken)
	TK::FLOAT					= Class.new(Token)
	TK::FOLLOWING			= Class.new(IDKeywordToken)
	TK::FOR						= Class.new(IDKeywordToken)
	TK::FOREIGN				= Class.new(KeywordToken)
	TK::FROM					= Class.new(KeywordToken)
	TK::GE						= Class.new(Token)
	TK::GENERATED			= Class.new(IDKeywordToken)
	TK::GROUP					= Class.new(KeywordToken)
	TK::GROUPS				= Class.new(IDKeywordToken)
	TK::GT						= Class.new(Token)
	TK::HAVING				= Class.new(KeywordToken)
	TK::ID						= Class.new(Token)
	TK::IF						= Class.new(IDKeywordToken)
	TK::IGNORE				= Class.new(IDKeywordToken)
	TK::ILLEGAL				= Class.new(Token)
	TK::IMMEDIATE			= Class.new(IDKeywordToken)
	TK::IN						= Class.new(KeywordToken)
	TK::INDEX					= Class.new(KeywordToken)
	TK::INDEXED				= Class.new(KeywordToken)
	TK::INITIALLY			= Class.new(IDKeywordToken)
	TK::INSERT				= Class.new(KeywordToken)
	TK::INSTEAD				= Class.new(IDKeywordToken)
	TK::INTEGER				= Class.new(Token)
	TK::INTERSECT			= Class.new(KeywordToken)
	TK::INTO					= Class.new(KeywordToken)
	TK::IS						= Class.new(KeywordToken)
	TK::ISNULL				= Class.new(KeywordToken)
	TK::JOIN					= Class.new(KeywordToken)
	TK::JOIN_KW				= Class.new(KeywordToken)
	TK::KEY						= Class.new(IDKeywordToken)
	TK::LAST					= Class.new(IDKeywordToken)
	TK::LE						= Class.new(Token)
	TK::LIKE_KW				= Class.new(IDKeywordToken)
	TK::LIMIT					= Class.new(KeywordToken)
	TK::LP						= Class.new(Token)
	TK::LSHIFT				= Class.new(Token)
	TK::LT						= Class.new(Token)
	TK::MATCH					= Class.new(IDKeywordToken)
	TK::MATERIALIZED	= Class.new(IDKeywordToken)
	TK::MINUS					= Class.new(Token)
	TK::NE						= Class.new(Token)
	TK::NO						= Class.new(IDKeywordToken)
	TK::NOT						= Class.new(KeywordToken)
	TK::NOTHING				= Class.new(KeywordToken)
	TK::NOTNULL				= Class.new(KeywordToken)
	TK::NULL					= Class.new(KeywordToken)
	TK::NULLS					= Class.new(IDKeywordToken)
	TK::OF						= Class.new(IDKeywordToken)
	TK::OFFSET				= Class.new(IDKeywordToken)
	TK::ON						= Class.new(KeywordToken)
	TK::OR						= Class.new(KeywordToken)
	TK::ORDER					= Class.new(KeywordToken)
	TK::OTHERS				= Class.new(IDKeywordToken)
	TK::OVER					= Class.new(KeywordToken)
	TK::PARTITION			= Class.new(IDKeywordToken)
	TK::PLAN					= Class.new(IDKeywordToken)
	TK::PLUS					= Class.new(Token)
	TK::PRAGMA				= Class.new(IDKeywordToken)
	TK::PRECEDING			= Class.new(IDKeywordToken)
	TK::PRIMARY				= Class.new(KeywordToken)
	TK::PTR						= Class.new(Token)
	TK::QUERY					= Class.new(IDKeywordToken)
	TK::RAISE					= Class.new(IDKeywordToken)
	TK::RANGE					= Class.new(IDKeywordToken)
	TK::RECURSIVE			= Class.new(IDKeywordToken)
	TK::REFERENCES		= Class.new(KeywordToken)
	TK::REINDEX				= Class.new(IDKeywordToken)
	TK::RELEASE				= Class.new(IDKeywordToken)
	TK::REM						= Class.new(Token)
	TK::RENAME				= Class.new(IDKeywordToken)
	TK::REPLACE				= Class.new(IDKeywordToken)
	TK::RESTRICT			= Class.new(IDKeywordToken)
	TK::RETURNING			= Class.new(KeywordToken)
	TK::ROLLBACK			= Class.new(IDKeywordToken)
	TK::ROW						= Class.new(IDKeywordToken)
	TK::ROWS					= Class.new(IDKeywordToken)
	TK::RP						= Class.new(Token)
	TK::RSHIFT				= Class.new(Token)
	TK::SAVEPOINT			= Class.new(IDKeywordToken)
	TK::SELECT				= Class.new(KeywordToken)
	TK::SEMI					= Class.new(Token)
	TK::SET						= Class.new(KeywordToken)
	TK::SLASH					= Class.new(Token)
	TK::SPACE					= Class.new(Token)
	TK::STAR					= Class.new(Token)
	TK::STRING				= Class.new(Token)
	TK::TABLE					= Class.new(KeywordToken)
	TK::TEMP					= Class.new(IDKeywordToken)
	TK::THEN					= Class.new(KeywordToken)
	TK::TIES					= Class.new(IDKeywordToken)
	TK::TO						= Class.new(KeywordToken)
	TK::TRANSACTION		= Class.new(KeywordToken)
	TK::TRIGGER				= Class.new(IDKeywordToken)
	TK::UNBOUNDED			= Class.new(IDKeywordToken)
	TK::UNION					= Class.new(KeywordToken)
	TK::UNIQUE				= Class.new(KeywordToken)
	TK::UPDATE				= Class.new(KeywordToken)
	TK::USING					= Class.new(KeywordToken)
	TK::VACUUM				= Class.new(IDKeywordToken)
	TK::VALUES				= Class.new(KeywordToken)
	TK::VARIABLE			= Class.new(Token)
	TK::VIEW					= Class.new(IDKeywordToken)
	TK::VIRTUAL				= Class.new(IDKeywordToken)
	TK::WHEN					= Class.new(KeywordToken)
	TK::WHERE					= Class.new(KeywordToken)
	TK::WINDOW				= Class.new(KeywordToken)
	TK::WITH					= Class.new(IDKeywordToken)
	TK::WITHOUT				= Class.new(IDKeywordToken)
end
