require:
  - standard
  - standard-custom
  - rubocop-minitest
  - rubocop-rake

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml

AllCops:
  NewCops: enable

Layout/IndentationStyle:
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Width: 1

Style/GlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
  Exclude:
    - 'test/feather/test_lexer.rb'

Minitest/AssertEmptyLiteral:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Exclude:
    - 'lib/feather/tokens.rb'
    - 'lib/feather/lexer/character.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'lib/feather/lexer/character.rb'
    - 'lib/feather/lexer/characters.rb'
    - 'lib/feather/lexer/keywords.rb'

Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'lib/feather/tokens.rb'